version: '3'

services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: terminology

    ports:
      - 5432:5432
    hostname: localhost
