# Generated by Django 3.2.7 on 2021-09-18 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='version',
        ),
        migrations.RemoveField(
            model_name='guideitem',
            name='guide_id',
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Короткое наименование'),
        ),
        migrations.CreateModel(
            name='GuideVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Название версии')),
                ('date_created', models.DateTimeField(verbose_name='Время начала действия')),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide')),
            ],
            options={
                'db_table': 'guide_version',
            },
        ),
        migrations.AddField(
            model_name='guideitem',
            name='parent_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guide_item', to='guide.guideversion'),
            preserve_default=False,
        ),
    ]
