# Generated by Django 3.2.7 on 2021-09-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_guideversion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideitem',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_item', to='guide.guideversion', verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='guideversion',
            name='guide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide', verbose_name='Справочник'),
        ),
    ]
